### PR TITLE
Dyes! And new textures that auri doesnt like!!

### PR DESCRIPTION
**Pull request by enjarai**

### CODE REVIEW

**Comment by StellarWitch7** [comment]
What is [this](https://github.com/enjarai/trickster/pull/57/files#diff-b7250e7b89e70047a4ad029f4add8f2623e1528c3e4588c3306dd2cddfda7298R73-R88).

**Comment by enjarai** [comment]
Ah uh, oops. Left that in by accident!

**Comment by StellarWitch7** [comment]
Also why is the default signed scroll using a different coloured ribbon?

**Comment by enjarai** [comment]
Because it looks nice :3

**Comment by StellarWitch7** [comment]
It's the only one...

**Comment by enjarai** [comment]
Correct, because its the only neutral one.

**Comment by StellarWitch7** [comment]
But. Black would look good on it too.

**Comment by StellarWitch7** [comment]
The quill isn't different on the neutral scroll and quill, why would the written one be any different with the ribbon?

**Comment by enjarai** [comment]
I mean, I thought it looked nicer I guess

**Comment by StellarWitch7** [comment]
Hm...
image
image

**Comment by StellarWitch7** [comment]
Alright, fine. Good to merge.

**Review by StellarWitch7 — APPROVED** [review]

**Comment by enjarai** [comment]
:D

**Pull request merged**
