### PR TITLE
[Feature] Add a keybind for editing spells on any item

### PR DESCRIPTION
**Pull request by Awakened-Redstone**
This adds a keybind, default F6, to allow creative players to edit spells on any item, allowing you to easily test your spells by editing your wand or other items you want to have the spell on. 
It differs from the mirror as only the full built spell is run instead of being run when drawn

### CODE REVIEW

**Review by StellarWitch7 — APPROVED** [review]
Looks good. I have no complaints, @enjarai.

**Review by enjarai — APPROVED** [review]
Made a small fix, is good now :3

**Review by enjarai — APPROVED** [review]

**Comment by StellarWitch7** [comment]
Actually @enjarai, I liked the behaviour of it never being greedy.

**Review by Awakened-Redstone — COMMENTED** [review]
:3

**Pull request merged**
