### PR TITLE
Make registries good :)

### PR DESCRIPTION
**Pull request by Dev0Louis**

### CODE REVIEW

**Comment by StellarWitch7** [comment]
Did you test this with an old world.
image

**Comment by Dev0Louis** [comment]
> Did you test this with an old world. image

No I not, I will check that :)

**Comment by StellarWitch7** [comment]
This is a strange one. Not sure why exactly, but the mirror doesn't appear to evaluate on this branch.

**Comment by Dev0Louis** [comment]
What? The only thing that I can think off is that somehow static init changing order destroyed it.

**Comment by StellarWitch7** [comment]
Merging `master` into this branch appears to have solved the issue somehow... good to merge.

**Review by StellarWitch7 — APPROVED** [review]

**Comment by Dev0Louis** [comment]
My Favorite kinda of Problem, one that is not solved by me :)

**Comment by StellarWitch7** [comment]
I merged this locally, as it appears that GitHub simply didn't like the pull request. Closing this PR now.

**Pull request closed without merging**
